### ISSUE TITLE
issue in FloTools

### ISSUE THREAD

**Issue by animamotrix** [flotools/flotools#1]
Hi,
not sure who will get this, but in any case hello to Slau and Kim (to which had a phone conversation a while ago), this is Marc Wagnon, and I have to say first that FloTools is a great development, Congratulation!
I encountered a couple of issues, and I am wondering if you are aware of them the first is the:
Edit Grid Value: Command+f8 (twice)
it says "type grid value"and I hear a Tink but it does not interact with the counter.
The second is with: Plugin monitor (option + /) it says "plugin monitor off" and I do not anything happening when I move the cursors on my surface. on the other hand it says "deactivate plugin monitor" correctly.
Anyway you might be aware of these, and if so, have you fixed the script?
I am running El Capitain and ProTools 10.6

Thanks for the great work,
Marc

**Comment by ghost** [comment]
Hi Marc,

Unfortunately Flo Tools does not support Pro Tools 10. It supports Pro 
Tools version 12.3 and up.

There have been some changes in string values before 12.3, so it could 
be one of those.

Unfortunately none of us has Pro Tools 10, so can't confirm the behavior.

Chi

**Comment by animamotrix** [comment]
Hi Chi,

Sorry my bad I mistyped i’m running 12.6 not 10.6

**Comment by ghost** [comment]
As far as grid value, can you type the value after you clicking it with 
mouse without using Flo Tools?

Can you try the plugin monitor with eq3- 1 band?
Make sure the plugin window is focused and active in front most window.
Then press option+slash. It should say watching plugin eq3 1 band.
Let me know how it goes.

**Comment by animamotrix** [comment]
Hi Chi,
when interacting with the grid/nudge cluster and selecting grid control a contextual menu opens, and you can select a value, actually you cannot type into it at all, but FloTools says type grid value, so that would never work.
As for the plug in controller, I was try it to change the volume value in the mixer, I understand now that it is meant only for plugins. 
While I am on the subject, I saw a few weeks ago on the protools access group a talk about having this arrow key controlling the volume and pan, is this coming online soon?

Thanks, Marc

**Comment by ghost** [comment]
Thanks for confirming it for grid value.

That's the exact behavior we're experiencing, and trying to figure it 
out whether you can actually ever edit it like nudge value.

As far as changing it to a preset value, you can use command+option+f8.
