### ISSUE TITLE
Resizing track list

### ISSUE THREAD

**Issue by jpabloc** [flotools/flotools#2]
Running latest protools 12.8.1. When call the marco to resizing the track list, the results of keyboard maestro are:
/var/folders/3t/xlhnkds91f109n98hs401xm00000gn/T/Keyboard-Maestro-Script-422E19BE-0D20-46D9-A50C-199CA57C490C:244:271: execution error: Error on line 8: Error: Can't get object. (-1728)
Even with the tracklist vissible.

**Comment by ghost** [comment]
It looks like it can't find the track list table.
Just to make sure, can you open a new session, create a few tracks, 
interact with the track list table with VoiceOver and see if you can 
find all the tracks inside the table?
Is your Pro Tools interface in non-English?

**Comment by jpabloc** [comment]
Hello. I just did it. In my main computer and in a macbook pro.

In both cases, I opened a new session with the same ressults in both machine.
All the interface (OSx, protools, keyboard) are set to Us english.

Is it possible that even vissible for voice over, the track list is covered by annother object in the window?
Because when I hide the clip list, the same error happens.

JP.
On 3 Sep 2017, at 10:40, amtlab <notifications@github.com<mailto:notifications@github.com>> wrote:

It looks like it can't find the track list table.
Just to make sure, can you open a new session, create a few tracks,
interact with the track list table with VoiceOver and see if you can
find all the tracks inside the table?
Is your Pro Tools interface in non-English?

**Comment by chigkim** [comment]
The floating transport window was hiding track list table.

**Comment by jpabloc** [comment]
yes. Thanks. I just was writting about that, I spoke with slau today morning.
